services:
  - type: web
    name: smart-hms-backend
    env: python
    plan: starter
    buildCommand: cd smart_hms/backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd smart_hms/backend && gunicorn hospital.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: smart-hms-backend.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/
